In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Online Retail/online_retail_II.csv')
print(df.shape)
print(df.head())

(1067371, 8)
  Invoice StockCode                          Description  Quantity  \
0  489434     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12
1  489434    79323P                   PINK CHERRY LIGHTS        12
2  489434    79323W                  WHITE CHERRY LIGHTS        12
3  489434     22041         RECORD FRAME 7" SINGLE SIZE         48
4  489434     21232       STRAWBERRY CERAMIC TRINKET BOX        24

           InvoiceDate  Price  Customer ID         Country
0  2009-12-01 07:45:00   6.95      13085.0  United Kingdom
1  2009-12-01 07:45:00   6.75      13085.0  United Kingdom
2  2009-12-01 07:45:00   6.75      13085.0  United Kingdom
3  2009-12-01 07:45:00   2.10      13085.0  United Kingdom
4  2009-12-01 07:45:00   1.25      13085.0  United Kingdom

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  object
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.1+ MB

In [4]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [5]:
# Drop Nulls
df = df.dropna(subset=['Customer ID', 'Description'])

# Remove Cancelled Orders
df = df[~df['Invoice'].astype(str).str.startswith('C')]

# 4 — fix date type
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

# 5 — fix Customer ID to integer
df['Customer ID'] = df['Customer ID'].astype(int)

# 6 — add TotalPrice
df['TotalPrice'] = df['Quantity'] * df['Price']

# check result
print(df.shape)
print(df.dtypes)
print(df.head())

(805620, 9)
Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
Price                 float64
Customer ID             int64
Country                object
TotalPrice            float64
dtype: object
  Invoice StockCode                          Description  Quantity  \
0  489434     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12
1  489434    79323P                   PINK CHERRY LIGHTS        12
2  489434    79323W                  WHITE CHERRY LIGHTS        12
3  489434     22041         RECORD FRAME 7" SINGLE SIZE         48
4  489434     21232       STRAWBERRY CERAMIC TRINKET BOX        24

          InvoiceDate  Price  Customer ID         Country  TotalPrice
0 2009-12-01 07:45:00   6.95        13085  United Kingdom        83.4
1 2009-12-01 07:45:00   6.75        13085  United Kingdom        81.0
2 2009-12-01 07:45:00   6.75        13085  United Kingdom        81.0
3 2009-12-01 07:45:00   2.10        13085  United Kingdom       100.8
4 2009-12-01 07:45:00   1.25        13085  United Kingdom        30.0

In [7]:
df['Month'] = df['InvoiceDate'].dt.month
df['Year'] = df['InvoiceDate'].dt.year

df['YearMonth'] = df['InvoiceDate'].dt.to_period('M').astype(str)

In [8]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,TotalPrice,Month,Year,YearMonth
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,83.4,12,2009,2009-12
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0,12,2009,2009-12
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0,12,2009,2009-12
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,100.8,12,2009,2009-12
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.0,12,2009,2009-12

In [9]:
df = df.rename(columns={
    'Customer ID': 'CustomerID',
    'Price': 'UnitPrice'
})

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 805620 entries, 0 to 1067370
Data columns (total 12 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      805620 non-null  object
 1   StockCode    805620 non-null  object
 2   Description  805620 non-null  object
 3   Quantity     805620 non-null  int64
 4   InvoiceDate  805620 non-null  datetime64[ns]
 5   UnitPrice    805620 non-null  float64
 6   CustomerID   805620 non-null  int64
 7   Country      805620 non-null  object
 8   TotalPrice   805620 non-null  float64
 9   Month        805620 non-null  int32
 10  Year         805620 non-null  int32
 11  YearMonth    805620 non-null  object
dtypes: datetime64[ns](1), float64(2), int32(2), int64(2), object(5)
memory usage: 73.8+ MB

In [ ]:
df['YearMonth'] = df['Y'].astype(int)

In [11]:
file_path = '/content/drive/MyDrive/Colab Notebooks/Online Retail/clean_online_retail.csv'

df.to_csv(file_path, index=False)

In [12]:
import os
os.listdir('/content/drive/MyDrive/Colab Notebooks/Online Retail')

['online_retail_II.csv', 'clean_online_retail.csv']